"""add job descriptions table

Revision ID: 653baf9df516
Revises: 5649abd5e42a
Create Date: 2026-04-27 16:57:15.507104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '653baf9df516'
down_revision: Union[str, Sequence[str], None] = '5649abd5e42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_descriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_descriptions_id'), 'job_descriptions', ['id'], unique=False)
    op.add_column('company_research', sa.Column('jd_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'company_research', 'job_descriptions', ['jd_id'], ['id'])
    op.add_column('interview_questions', sa.Column('jd_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'interview_questions', 'job_descriptions', ['jd_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_questions', type_='foreignkey')
    op.drop_column('interview_questions', 'jd_id')
    op.drop_constraint(None, 'company_research', type_='foreignkey')
    op.drop_column('company_research', 'jd_id')
    op.drop_index(op.f('ix_job_descriptions_id'), table_name='job_descriptions')
    op.drop_table('job_descriptions')
    # ### end Alembic commands ###
