"""add company research table

Revision ID: 78980f3d63be
Revises: d5092a724041
Create Date: 2026-04-27 13:10:49.773942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78980f3d63be'
down_revision: Union[str, Sequence[str], None] = 'd5092a724041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_research',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('tech_stack', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('tips', sa.Text(), nullable=True),
    sa.Column('culture', sa.Text(), nullable=True),
    sa.Column('interview_process', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_research_id'), 'company_research', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_research_id'), table_name='company_research')
    op.drop_table('company_research')
    # ### end Alembic commands ###
