"""add interview reports table

Revision ID: e698c45c3152
Revises: d8f9c5ff2c94
Create Date: 2026-04-28 18:06:56.997622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e698c45c3152'
down_revision: Union[str, Sequence[str], None] = 'd8f9c5ff2c94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interview_id'), table_name='interview')
    op.drop_table('interview')
    op.drop_index(op.f('ix_interview_report_id'), table_name='interview_report')
    op.drop_table('interview_report')
    op.add_column('interview_reports', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('interview_reports', sa.Column('jd_id', sa.Integer(), nullable=False))
    op.add_column('interview_reports', sa.Column('session_id', sa.Integer(), nullable=False))
    op.add_column('interview_reports', sa.Column('overall_score', sa.Float(), nullable=True))
    op.add_column('interview_reports', sa.Column('strengths', sa.Text(), nullable=True))
    op.add_column('interview_reports', sa.Column('weaknesses', sa.Text(), nullable=True))
    op.add_column('interview_reports', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('interview_reports', sa.Column('recommendations', sa.Text(), nullable=True))
    op.add_column('interview_reports', sa.Column('topics_breakdown', sa.Text(), nullable=True))
    op.add_column('interview_reports', sa.Column('total_questions', sa.Integer(), nullable=True))
    op.add_column('interview_reports', sa.Column('answered', sa.Integer(), nullable=True))
    op.add_column('interview_reports', sa.Column('study_plan', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'interview_reports', 'interview_sessions', ['session_id'], ['id'])
    op.create_foreign_key(None, 'interview_reports', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'interview_reports', 'job_descriptions', ['jd_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interview_reports', type_='foreignkey')
    op.drop_constraint(None, 'interview_reports', type_='foreignkey')
    op.drop_constraint(None, 'interview_reports', type_='foreignkey')
    op.drop_column('interview_reports', 'study_plan')
    op.drop_column('interview_reports', 'answered')
    op.drop_column('interview_reports', 'total_questions')
    op.drop_column('interview_reports', 'topics_breakdown')
    op.drop_column('interview_reports', 'recommendations')
    op.drop_column('interview_reports', 'created_at')
    op.drop_column('interview_reports', 'weaknesses')
    op.drop_column('interview_reports', 'strengths')
    op.drop_column('interview_reports', 'overall_score')
    op.drop_column('interview_reports', 'session_id')
    op.drop_column('interview_reports', 'jd_id')
    op.drop_column('interview_reports', 'user_id')
    op.create_table('interview_report',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_report_pkey'))
    )
    op.create_index(op.f('ix_interview_report_id'), 'interview_report', ['id'], unique=False)
    op.create_table('interview',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('interview_pkey'))
    )
    op.create_index(op.f('ix_interview_id'), 'interview', ['id'], unique=False)
    # ### end Alembic commands ###
